name: flutter_ui_home_property
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-Regular.ttf
        - asset: assets/font/Outfit-Light.ttf
          weight: 300
        - asset: assets/font/Outfit-Medium.ttf
          weight: 500
        - asset: assets/font/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/font/Outfit-Bold.ttf
          weight: 700

